Add password policy
PrestaShop/hummingbird pull request #225
Opened 2022-04-04 15:42 UTC by NeOMakinG

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | We need to apply a some JS in order to show password policy tips
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go on register as a customer, type your password and have fun!
| Possible impacts? | Register as a customer

2022-04-05 07:20 UTC, PierreRambaud approved these changes

2022-04-06 08:32 UTC, mparvazi commented on src/js/components/usePasswordPolicy.ts
> +    feedbackContainer = element.querySelector<HTMLElement>(PasswordPolicyMap.container);
```suggestion

  if (feedbackTemplate && element && elementInput) {
    templateElement.innerHTML = feedbackTemplate.innerHTML;
    element.append(templateElement);
    const feedbackContainer = element.querySelector<HTMLElement>(PasswordPolicyMap.container);
```

2022-04-06 08:32 UTC, mparvazi commented on src/js/components/usePasswordPolicy.ts
> +        elementInput.addEventListener('keyup', () => watchPassword(elementInput, feedbackContainer!, hints));
```suggestion
        elementInput.addEventListener('keyup', () => watchPassword(elementInput, feedbackContainer, hints));
```

2022-04-06 08:32 UTC, mparvazi commented on src/js/components/usePasswordPolicy.ts
> +      if (hintElement) {
```suggestion
      if (hintElement && hintElement.innerHTML.trim()) {
```

2022-04-06 08:50 UTC, mparvazi commented
![Screenshot from 2022-04-06 13-20-31](https://user-images.githubusercontent.com/85633460/161935616-895d3557-ae1a-45a7-bc8d-81291a1d61d9.png)

2022-04-11 10:02 UTC, Progi1984 requested changes
Could you remove merge commits ?

2022-05-09 08:49 UTC, NeOMakinG commented
I'll leave this as a draft and not fixing things until it's merged on the core side, it will avoid me dealing with rebases and whatever :)

2022-10-19 09:45 UTC, atomiix commented
@NeOMakinG looks like there's a conflict 🙃

2022-12-06 14:50 UTC, NeOMakinG commented
@Hlavtox considering mparvarsi's review and stuff, can you check and approve/merge if it looks fine for you?

2022-12-07 09:13 UTC, NeOMakinG commented
@PrestaShop/prestashop-maintainers can I get a review from someone there? @Hlavtox told me that he was ready to merge it but I would like one more pair of eyes on it

2022-12-13 17:10 UTC, matthieu-rolland approved these changes

2022-12-14 09:12 UTC, Hlavtox approved these changes

2022-12-14 09:13 UTC, merged