Use accordions as categories with childs on categorytree
PrestaShop/hummingbird pull request #333
Opened 2022-07-06 08:32 UTC by NeOMakinG

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | On ps_categorytree, we want a cool design, easy to maintain, bootstrap collapse with the accordion style is a perfect fit for it!
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/hummingbird/issues/256.
| How to test?      | Go on category page, see screenshot
| Possible impacts? | categorytree

<img width="291" alt="image" src="https://user-images.githubusercontent.com/14963751/177506779-2c9f0a3c-d21f-4154-bc33-8d85de76cfeb.png">

2022-07-06 09:06 UTC, Hlavtox requested changes

2022-07-07 01:58 UTC, SharakPL commented
Some improvements to consider:
1. Utility classes are great, but I would avoid them inside loops. Especially big loops like menu or category tree. It's better to create a simple set of styles and target html tags or data-depth attributes than repeat a long lists of classes for each item.
2. `ul` determines the depth so that's where `data-depth` attribute should be places. No need to repeat it for every `li` element.
3. I never liked that only links of nodes with children are wrapped in a div. This makes whole thing harder to style, especially when only some nodes of the same depth have children. Every link should be wrapped the same way.
4. It's required to have current category branch shown by default so we need more states eg. `node.current=true` for current category and `node.active=true` for current category and all it's parents.

```smarty
<ul class="{$componentName}-list" data-depth="{$depth}">
  {foreach from=$nodes item=node name="categories"}
    <li class="{$componentName}-item {if $node.current}current{/if}">
      <div class="{$componentName}-item-header">
        <a class="{$componentName}-{if $depth===0}item{else}child{/if}-link" href="{$node.link}">{$node.name}</a>
        {if $node.children}
          <button class="collapsed" data-bs-toggle="collapse" data-bs-target="#exCollapsingNavbar{$node.id}"></button>
        {/if}
      </div>
      {if $node.children}
        <div class="collapse {if $node.active}show{/if}" id="exCollapsingNavbar{$node.id}">
          {categories nodes=$node.children depth=$depth+1}
        </div>
      {/if}
    </li>
  {/foreach}
</ul>
```

2022-07-07 13:07 UTC, Hlavtox commented
@SharakPL @NeOMakinG We should add a function to keep the current category open, a lot of client want this.

It was a nice feature of 1.6

2022-07-08 07:58 UTC, NeOMakinG commented
> @SharakPL @NeOMakinG We should sometime add a function to keep the current category open, a lot of client want this.
> 
> It was a nice feature of 1.6

We need to add this to a list somewhere or open an issue

2022-07-08 07:58 UTC, merged