Switch some images to picture tags
PrestaShop/hummingbird pull request #403
Opened 2022-12-07 10:59 UTC by NeOMakinG

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | We want to use picture tags everywhere we have some images and these parts were missing
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Images on every part should work as expected
| Possible impacts? | Images display

2022-12-07 16:18 UTC, Hlavtox commented on templates/checkout/_partials/order-confirmation-table.tpl
> +                {if !empty($product.default_image.legend)}
This is handled by the core, there will always be a legend. 👍 

`'legend' => !empty($object->meta_title) ? $object->meta_title : $object->name,`

2022-12-07 16:19 UTC, Hlavtox approved these changes
Just check the legends, good otherwise!

2022-12-07 17:08 UTC, SharakPL requested changes
Some indentations + legend @Hlavtox mentioned.
Also maybe we could limit the size of the tags eg. put `type` next to `source`:
```
<source type="image/avif"
  srcset="..."
>
```

2022-12-08 16:09 UTC, NeOMakinG commented
Thanks a lot for the review @SharakPL @Hlavtox , I'll fix that tomorrow

2022-12-09 10:19 UTC, Hlavtox approved these changes

2022-12-09 10:19 UTC, Hlavtox commented
@SharakPL Merge it when you check it ;-)

2022-12-09 10:42 UTC, SharakPL approved these changes

2022-12-09 10:43 UTC, merged

2022-12-15 14:00 UTC, Hlavtox commented on modules/productcomments/views/templates/hook/post-comment-modal.tpl
> +                          title="{$product.cover.legend}"
@NeOMakinG maybe > missing here? :D