Make blockwishlist compatible
PrestaShop/hummingbird pull request #408
Opened 2022-12-19 14:12 UTC by NeOMakinG

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Blockwishlist is not fully compatible with bootstrap 5
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test blockwishlist inside the theme
| Possible impacts? | Blockwishlist

2022-12-19 15:59 UTC, matks reviewed
@NeOMakinG Code is OK but license header can be updated

2022-12-19 15:59 UTC, matks commented on modules/blockwishlist/views/templates/components/modals/add-to-wishlist.tpl
> + * 2007-2020 PrestaShop and Contributors
2023 ? 😄 let's anticipate

2022-12-19 15:59 UTC, matks commented on modules/blockwishlist/views/templates/components/modals/create.tpl
> + * 2007-2020 PrestaShop and Contributors
Same

2022-12-19 16:09 UTC, nicosomb submitted a review, later dismissed

2022-12-19 17:07 UTC, NeOMakinG commented
> @NeOMakinG Code is OK but license header can be updated

Damn, I took those from blockwishlist directly, I'll update them as an override is now the responsibility of the theme!

2022-12-20 12:06 UTC, matthieu-rolland approved these changes

2022-12-20 12:40 UTC, nicosomb approved these changes

2023-01-05 12:37 UTC, kpodemski commented on modules/blockwishlist/views/templates/components/modals/rename.tpl
> +           >
```suggestion
           <label class="form-label" for="input2">((label))</label>
```

2023-01-05 12:42 UTC, JBLach commented on modules/blockwishlist/views/templates/components/modals/rename.tpl
> +           >
```suggestion
           <label class="form-label" for="input2">((label))</label>
```

2023-01-05 14:13 UTC, nicosomb approved these changes

2023-01-05 15:02 UTC, SharakPL submitted a review, later dismissed

2023-01-05 15:14 UTC, nicosomb submitted a review, later dismissed

2023-01-05 15:31 UTC, SharakPL requested changes
Last small fixes

2023-01-05 15:31 UTC, SharakPL commented on modules/blockwishlist/views/templates/components/modals/create.tpl
> +>
```suggestion
<div
  class="wishlist-create"
  data-url="{$url}"
  data-title="{l s='Create wishlist' d='Modules.Blockwishlist.Shop'}"
  data-label="{l s='Wishlist name' d='Modules.Blockwishlist.Shop'}"
  data-placeholder="{l s='Add name' d='Modules.Blockwishlist.Shop'}"
  data-cancel-text="{l s='Cancel' d='Modules.Blockwishlist.Shop'}"
  data-create-text="{l s='Create wishlist' d='Modules.Blockwishlist.Shop'}"
  data-length-text="{l s='List title is too short' d='Modules.Blockwishlist.Shop'}"
>
```

2023-01-05 15:31 UTC, SharakPL commented on modules/blockwishlist/views/templates/components/modals/add-to-wishlist.tpl
> +          </h5>
```suggestion
          <h5 class="modal-title">{l s='Add to wishlist' d='Modules.Blockwishlist.Shop'}</h5>
```

2023-01-05 15:31 UTC, SharakPL commented on modules/blockwishlist/views/templates/components/modals/create.tpl
> +            />
```suggestion
            <input
              type="text"
              class="form-control form-control-lg"
              v-model="value"
              id="input2"
              :placeholder="placeholder"
            >
```

2023-01-05 15:31 UTC, SharakPL commented on modules/blockwishlist/views/templates/components/modals/login.tpl
> + </div>
```suggestion
  <div
    class="modal-backdrop fade"
    {literal}
      :class="{in: !isHidden}"
    {/literal}
  >
  </div>
```

2023-01-05 15:31 UTC, SharakPL commented on modules/blockwishlist/views/templates/components/modals/rename.tpl
> +            />
```suggestion
            <input
              type="text"
              class="form-control form-control-lg"
              v-model="value"
              id="input2"
            >
```

2023-01-05 15:31 UTC, SharakPL commented on modules/blockwishlist/views/templates/components/modals/share.tpl
> +            />
```suggestion
            <input
              type="text"
              class="form-control form-control-lg"
              v-model="value"
              id="input2"
              placeholder="Share link"
            >
```

2023-01-05 15:39 UTC, NeOMakinG commented
I wish we had a linter for this

2023-01-05 15:56 UTC, SharakPL approved these changes

2023-01-05 16:01 UTC, SharakPL commented
> I wish we had a linter for this

2023-01-05 16:27 UTC, kpodemski approved these changes

2023-01-05 22:46 UTC, merged

2023-01-05 22:46 UTC, kpodemski commented
🍬 @NeOMakinG :D

2023-01-06 08:29 UTC, NeOMakinG commented
> 🍬 @NeOMakinG :D

<iframe src="https://giphy.com/embed/3orif180X6PAeh02d2" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/season-12-the-simpsons-12x11-3orif180X6PAeh02d2">via GIPHY</a></p>