Preload material icons, allow to preload other fonts
PrestaShop/hummingbird pull request #427
Opened 2023-01-08 00:23 UTC by Oksydan

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | CLS in header caused by material icons can be reduced by preloading material icons font. Unfortunately that icon font with version > 6.X got some weight. It is 125 KB for .woff2 format which is rly high. Comparing it to version that is classic theme using it's twice as heavy. I was thinking about preloading font via query param added to font-face src but it is impossible via `webpack-font-preload-plugin` plugin since it is including files query params with extension. It causing to fail at isFont condition. We can think about forking it or create our own plugin. 
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/hummingbird/issues/252 - partially 
| How to test?      | Build theme and check waterfall in network tab and loading of fonts in FO.
| Possible impacts? | no

Comparison - throttling 3G fast:

### Before:

https://user-images.githubusercontent.com/25306716/211175116-77de21e3-9e3b-446c-a00e-40731ae744aa.mov

### After:

https://user-images.githubusercontent.com/25306716/211175123-10a10083-1353-4ee3-b193-d39f03351a59.mov

2023-01-08 21:01 UTC, NeOMakinG approved these changes
That's cool we needed it, forking is most of the time increasing the maintenance cost more than anything

Anyway, even my comment is nitpicking so it's a 🍬 for me!

2023-01-08 21:26 UTC, Oksydan commented on templates/_partials/preload.tpl
> +{/if}
Hmm I am not sure how we could achieve it easily, path to file might be different between environments. We can't predict relative path to file or absolute at build time.

2023-01-09 08:14 UTC, 0x346e3730 approved these changes

2023-01-09 09:38 UTC, Oksydan commented on templates/_partials/preload.tpl
> +{/if}
I didn't notice that I assigned variable there for no reason 🤔. 
I am fixing it

2023-01-09 16:07 UTC, NeOMakinG approved these changes

2023-03-31 15:08 UTC, kpodemski requested changes
It's been a while... I wanted to approve it and merge it, but there's a package-lock conflict.

2023-04-03 22:42 UTC, Oksydan commented
@kpodemski branch rebased. 
Looks like some dependencies were missing in pacakge-lock.json 🤔

2023-05-08 11:46 UTC, kpodemski approved these changes

2023-05-08 11:52 UTC, kpodemski requested changes
I wanted to accept it again, but you added Swiper.js. Not sure what's the reason. I don't see the usage of Swiper in Hummingbird.

2023-05-08 12:09 UTC, Oksydan commented
@kpodemski fixed. 
Looks like i did mistake during rebase process. 
Swiper has been removed here https://github.com/PrestaShop/hummingbird/commit/5a654afcf5bc382e9d9f7eb01f58e96047a43492 - it's been here when I was working with this feature.

2023-05-08 12:42 UTC, kpodemski commented
@Hlavtox this has to be QA'd by a dev, do you think PS SA devs could help you with that?

2023-06-22 18:00 UTC, kpodemski commented
@ga-devfront @GytisZum guys, could you validate this PR? let me know if it looks ok for you

2023-06-23 06:23 UTC, ga-devfront reviewed
Thank's for your work, I just add one question about the configuration.

2023-06-23 06:23 UTC, ga-devfront commented on webpack/webpack.parts.js
> +      extensions: ['woff2'],
Why only `woff2` I know `eot` is only for IE and we don't support it but `ttf` is supported by all browser.

2023-07-31 20:36 UTC, merged

2023-07-31 20:36 UTC, kpodemski commented
thanks @Oksydan ;-)