Update category-header.tpl
PrestaShop/hummingbird pull request #477
Opened 2023-03-27 16:13 UTC by rodriciru

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Please be specific when describing this change. What did you change? Why?
| Type?             | bug fix / improvement / new feature / refactor
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | Indicate how to verify that this change works as expected.

2023-03-27 20:01 UTC, sudo-do submitted a review, later dismissed
Since I don't see a reason to get invalid index in line 14.

2023-03-28 09:20 UTC, mflasquin requested changes

2023-03-28 09:20 UTC, mflasquin commented on templates/catalog/_partials/category-header.tpl
> +            {if !empty($category.image}
```suggestion
            {if !empty($category.image) && !empty($category.image.large.url)}
```

2023-03-28 09:53 UTC, sudo-do commented on templates/catalog/_partials/category-header.tpl
> +            {if !empty($category.image}
isn't large url exist if image exists?

2023-03-28 10:23 UTC, rodriciru reviewed
Not necessary IMO

2023-03-28 10:24 UTC, rodriciru commented
I dont know how to reject this changes, so i hope i do it ok

2023-03-28 10:27 UTC, sudo-do commented
yeah, the change is not nessesary as far as i know prestashop environment

2023-03-31 11:32 UTC, Hlavtox approved these changes

2023-04-03 14:17 UTC, Hlavtox commented
@rodriciru Can you show what error you are getting? I deleted the images from the category but I get no error 🤔

2023-04-24 10:52 UTC, kpodemski commented
@rodriciru that's odd, `empty` for this key should be safe 🤔  have you checked this file 078ccc9839dcacadc15c0f4aa16f402af5079aa_2.file.category.tpl.php on line 57 to see if it is really about this line?

2023-04-25 08:48 UTC, rodriciru commented
> @rodriciru that's odd, `empty` for this key should be safe 🤔 have you checked this file 078ccc9839dcacadc15c0f4aa16f402af5079aa_2.file.category.tpl.php on line 57 to see if it is really about this line?

Yep, it's weird as hell, but I have some answers.
Looking at compiled PHP, I see that some empty functions translate to simple `if`'s and others don't.
Concretely, this image `empty `translates to `if `and the `empty `2 lines above translate to an `empty `instead of an `if`:
**PLEASE KEEP IN MIND It's NOT EXACTLY THIS FILE, BUT IT'S ALMOST THE SAME**
```
            <?php if ($_smarty_tpl->tpl_vars['category']->value['image']) { ?>
                <div class="category-cover">
                  <img src="<?php echo htmlspecialchars((string) $_smarty_tpl->tpl_vars['category']->value['image']['large']['url'], ENT_QUOTES, 'UTF-8'); ?>
" alt="<?php if (!empty($_smarty_tpl->tpl_vars['category']->value['image']['legend'])) {
                  echo htmlspecialchars((string) $_smarty_tpl->tpl_vars['category']->value['image']['legend'], ENT_QUOTES, 'UTF-8');
                } else {
                  echo htmlspecialchars((string) $_smarty_tpl->tpl_vars['category']->value['name'], ENT_QUOTES, 'UTF-8');
                } ?>">
                </div>
            <?php } ?>
```
Effectively, `empty` not raises any warnings, but `if` does, so this is why we get the warning.
Still, I think this is an easy and no harmful at all fix, even if the blame of the issue is smarty

2023-07-31 08:48 UTC, leemyongpakvn commented
@florine2623 FYI, hummingbird is different from classic-theme. There is no `_dev` directory in hummingbird, you need to create a .env file inside its webpack directory, and run `npm run build` from hummingbird directory following this _cookbook_ https://github.com/PrestaShop/hummingbird#how-to-build-assets ;)

2023-12-06 13:41 UTC, florine2623 commented
Hello @rodriciru ,

It seems like no one can reproduce your issue, neither @Hlavtox , @kpodemski nor @leemyongpakvn .

Could you explain further so it can be reproduced and tested ?

2023-12-08 00:51 UTC, leemyongpakvn commented
As usual, QA will close the issue if they can not reproduce it :ok_hand:

2023-12-08 01:49 UTC, Hlavtox commented
@rodriciru I will try to reproduce once again, if you really say it happens. There is no reason for smarty to convert empty to if. If it does so, it's stupid. 🤔

On what core version you are getting this behavior?

2023-12-08 12:21 UTC, Prestaworks commented
{if !empty($category.image.large.url)} is also present in classic theme, I tried deleting the category images, "image" => null shows on the category dump, tested on PS 8.1.2 and php 7.2, 7.4 and 8.1 still nothing in the php logs or Prestashop log files.

so if this is caused by "image" not existing it's maybe an older PS version?
To make the check safe it should maybe be something like
{if !empty($category.image) && !empty($category.image.large)} 

But I can't recreate the error on PS 8.1.2.

2023-12-08 12:40 UTC, rodriciru commented
I don't remember exactly the version, but I try to keep the latest version
of ps on my stores. So by the time the issue is created, the most recent
version at that time.

Anyway,seeing I'm the only,and can't reproduce by any of yours, let's close
and will open a new one if happens again

El vie, 8 dic 2023 13:21, Daniel ***@***.***> escribió:

> {if !empty($category.image.large.url)} is also present in classic theme, I
> tried deleting the category images, "image" => null shows on the category
> dump, tested on PS 8.1.2 and php 7.2, 7.4 and 8.1 still nothing in the php
> logs or Prestashop log files.
>
> so if this is caused by "image" not existing it's maybe an older PS
> version?
> To make the check safe it should maybe be something like
> {if !empty($category.image) && !empty($category.image.large)}
>
> But I can't recreate the error on PS 8.1.2.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PrestaShop/hummingbird/pull/477#issuecomment-1847079663>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACR6MY62QUHA77W2K7T6RCDYIMA33AVCNFSM6AAAAAAWJLLUUWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNBXGA3TSNRWGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-15 10:17 UTC, kpodemski commented
@Hlavtox @Prestaworks maybe it was a bug in some Smarty version because I noticed that problem as well, I've had `{if !empty($array.key)}` it started flooding logs with a warnings/notice.

2023-12-15 10:36 UTC, kpodemski commented
@rodriciru 1.7.6 something

2024-07-09 08:57 UTC, florine2623 commented
I suggest closing this issue as it cannot be reproduced https://github.com/PrestaShop/hummingbird/issues/476#issuecomment-1864780014

2024-07-09 08:57 UTC, closed without merging