Edit payment option to work with ps_checkout
PrestaShop/hummingbird pull request #533
Opened 2023-07-28 13:49 UTC by tblivet

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Payment option display has been edited to make **ps_checkout** display properly
| Type?             | bug fix / improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | --
| Sponsor company   | @PrestaShopCorp
| How to test?      | Not easy to test because the shop must have **ps_checkout** configure, but this should render the payment option like in the screen below : top -> before & bottom -> after ![image](https://github.com/PrestaShop/hummingbird/assets/110676325/519e3161-c91a-465c-9f9b-9e6a7bbeefe4)

2023-07-31 07:57 UTC, kpodemski requested changes
ps_checkout is not a native module, this is why the fix shouldn't be there

if changes in .tpl are valid for other payment methods, it's ok, but CSS rules shouldn't be part of Hummingbird

you can easily add it to your version of the theme, or contribute to ps_checkout to display correctly if the theme is Hummingbird

2023-07-31 07:57 UTC, kpodemski commented on src/scss/custom/modules/_checkout.scss
> +.payment__option {
This shouldn't be inside core of Hummingbird but rather inside your theme or ps_checkout module :)

2023-07-31 09:27 UTC, tblivet commented
Hello @kpodemski !
I have removed the CSS related to "ps_checkout".
I think the template is still relevant because it improves the display of payment option in case we have an image.

2023-07-31 09:28 UTC, kpodemski approved these changes

2023-08-04 07:42 UTC, aniszr approved these changes
Hello @tblivet 
I tested your PR, the checkout options are well displayed, LGTM :heavy_check_mark: 
QA :heavy_check_mark: 

See attached screenshot :
![image](https://github.com/PrestaShop/hummingbird/assets/92626242/124190e5-d911-4f66-a6b0-e973692b56a4)

Thanks!

2023-08-04 09:02 UTC, merged

2023-08-04 09:02 UTC, nicosomb commented
Thank you @tblivet !