fix: quantity input of additional products have an issue after changing quantity of a product in the cart
PrestaShop/hummingbird pull request #541
Opened 2023-08-10 16:57 UTC by tblivet

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Correct the issue 540
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/hummingbird/issues/540
| Sponsor company   | @PrestaShopCorp
| How to test?      | You can refer to the issue

2023-08-15 08:53 UTC, Hlavtox commented
Seems that built assets got into the PR

2023-08-22 09:44 UTC, kpodemski requested changes, later dismissed
Compiled assets shouldn't be versioned.

2023-08-25 08:45 UTC, tblivet commented
The compiled files are removed !

2023-08-31 08:34 UTC, ancardinale approved these changes

2023-09-05 12:39 UTC, ga-devfront commented
No response from the people who blocked the PR and the changes are be done.
I pass the PR to Waiting for QA

2023-09-05 12:39 UTC, ga-devfront submitted a review, later dismissed

2023-09-05 12:52 UTC, ancardinale approved these changes

2023-09-06 11:26 UTC, davidglezz commented on src/js/constants/selectors-map.ts
> +  productCartList: '.cart__items .js-quantity-button',
Looks like this is not a good place

It contains selectors of `qtyInput` parts, not where `qtyInput` is placed

maybe inside `cart` const? `cart.productQuantity`

2023-09-06 15:07 UTC, djoelleuch approved these changes, later dismissed
Hello @tblivet  
LGTM ,

https://github.com/PrestaShop/hummingbird/assets/115152460/2910e1fa-ab18-4ec0-b52d-693cc618f6d0




It's QA approved ✔️
thank you !

2023-09-07 13:46 UTC, ga-devfront approved these changes

2023-09-07 13:47 UTC, merged