fix: when you edit the product qty to zero, the product won't be removed from the cart
PrestaShop/hummingbird pull request #542
Opened 2023-08-10 17:21 UTC by tblivet

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Correct the issue 536
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/hummingbird/issues/536
| Sponsor company   | @PrestaShopCorp
| How to test?      | You can refer to the issue

2023-08-14 13:30 UTC, matks approved these changes, later dismissed
Looks good to me 👍 

ping @ga-devfront for 2nd opinion

2023-08-15 08:42 UTC, SharakPL commented
IMO it would be better to simply disallow changing quantity to 0. This can be done by mistake and then it would have to be searched again. If a user wants to remove the product from the cart then the Remove button should be clicked.

2023-08-15 08:51 UTC, Hlavtox commented
@SharakPL That was how it was before. It should throw an error message "Minimal quantity for sale is 1".

Also, it's a bit incosistent. What does it do if minimum quantity for sale is higher than 1? 🤔

I am a bit torn apart for the expected behavior here.

2023-08-15 14:59 UTC, sallemiines approved these changes
Hello @tblivet 

Thanx for the PR ! LGTM QA :heavy_check_mark: 

https://github.com/PrestaShop/hummingbird/assets/31663369/7140700b-7cf9-4281-9bfc-aaa01023d520


Thank you :rocket:

2023-08-15 15:10 UTC, sallemiines approved these changes, later dismissed
Hello @tblivet 

Thanx for the PR ! LGTM QA :heavy_check_mark: 


https://github.com/PrestaShop/hummingbird/assets/31663369/0e0b481e-c8a6-4014-8163-64b8542ee07c




Thank you :rocket:

2023-08-15 15:36 UTC, SharakPL commented
@sallemiines could you please check again with product that has minimum order quantity higher than 1? It doesn't look like it's covered.

2023-08-15 16:04 UTC, FabienPapet submitted a review, later dismissed
blocking as we need to check before merge

2023-08-21 15:22 UTC, MhiriFaten reviewed
Merging is blocked, I will remove the **`waiting for QA`** label until the changes requests are resolved.

2023-08-22 09:41 UTC, kpodemski requested changes, later dismissed
I wanted to agree with @Hlavtox and @SharakPL, but I've just tested it on PS 8.1 with Classic, and it works like this:

The behavior should be as follows:
1. If you change from 1 to 0 using arrows, the product is deleted.
2. If you change from 1 to 0 using the input value, the product is deleted.
3. If you have a product with a minimal quantity set to 2 and you change it to 1, you have an error.

Why does it work in Classic, and it doesn't work with Hummingbird?
What's the difference between Classic and Humminbird?

If you have 1 unit in your shopping cart and you change it to 0 (either by using arrows or input), the request goes to `delete` action. In Hummingbird, it always goes to the `update` action, which is wrong.

This PR almost fixes the issue but there's a problem with getting a minimal quantity which could be different than 1.

2023-08-22 09:43 UTC, kpodemski commented
@tblivet Related function in Classic is inside:

themes/classic/_dev/js/cart.js in `updateProductQuantityInCart` function.

```
if (targetValue === '0') {
      $target.closest('.product-line-actions').find('[data-link-action="delete-from-cart"]').click();
    } else {
      $target.attr('value', targetValue);
      sendUpdateQuantityInCartRequest(updateQuantityInCartUrl, getRequestData(qty), $target);
    }
```

It looks that instead of checking minimal quantity you should only check whether the target value is equal to 0.

2023-08-23 15:55 UTC, SharakPL commented
Is there a place for improvements or does it have to be done like in Classic?

2023-08-23 16:01 UTC, kpodemski commented
@SharakPL what would be an improvement in your opinion?

2023-08-23 16:14 UTC, SharakPL commented
To be more clear on what each action does. Decreasing the amount shouldn't delete the product from the cart.
If the requested amount is lower than the minimum required for order then it should throw an error:

> The minimum amount required for order of this product is X. If you want to remove the product completely from your cart then use the Remove button

Or at least change [ - ] to [ X ] to indicate  that next use of this button will remove it completely instead of just decreasing the amount. Especially useful if the minimum required amount is higher than 1.

2023-08-23 16:22 UTC, kpodemski commented
The one improvement I see in this change is that if one makes a mistake and changes the value below 1, it could save the cart. I've checked a few stores, and when there are arrows, changing below 0 is forbidden. There's no request, which could also be a good thing.

Something to be decided by @PrestaShop/product-council :)

To summarize:
- If you change the value below 1, it should inform about minimal quantity or doesn't do anything.

2023-08-24 07:37 UTC, SharakPL commented
> I've checked a few stores, and when there are arrows, changing below 0 is forbidden.

Did you mean "below 1"?

2023-08-24 07:39 UTC, kpodemski commented
@SharakPL yes, I edited the message

2023-08-24 08:16 UTC, Hlavtox commented
@RosaBenouamer There needs to be a number input, dropdown for selecting count is not good UX. :-)

2023-08-31 08:50 UTC, jolelievre commented on src/js/pages/cart.ts
> +        if (targetValue && targetValue.getAttribute('value') === '1' && targetValue.getAttribute('min') === '1') {
Be careful the min quantity can also be 0 which should be handled like 1, meaning the feature is disabled there is no minimum
Except that I think the original behaviour from classic is consistent and should be used as a base as it's a common way to handle this in many e-commerce shops

tldr; let's stay iso functional

2023-08-31 08:52 UTC, jolelievre commented on src/js/pages/cart.ts
> +        if (targetValue && targetValue.getAttribute('value') === '1' && targetValue.getAttribute('min') === '1') {
Ah and one other comment you seem to be listening to the click event, so only the arrows clicking but the value can also be edited via keyboard, so you should either listen to the `keydown` event as well or maybe easier simply the `change` event?

Unless you need to listen to the specific event to cancel it when the value is not the minimum one?

2023-08-31 16:40 UTC, tblivet commented
Hello 👋 With @ga-devfront we have update the PR we now have this behavior :
- When we click on decrement to go from 1 to 0 -> product is deleted
- When we click on decrement to go from 5 to 4 when product has minimum qty of 5 -> product is not deleted error message appear and qty remain the same.
- When we change the quantity manually (without + or - ) to 0 -> product is deleted
- When we change the quantity manually (without + or - ) to 0 and the product have minimum qty -> product is not deleted error message appear and qty remain the same.

2023-09-05 12:39 UTC, ga-devfront approved these changes

2023-09-06 11:35 UTC, davidglezz commented on src/js/pages/cart.ts
> +      }
```suggestion
      if (!removeButton || !targetValue) {
        return;
      }
      
      if (eventTarget.classList.contains('js-increment-button')) {
        if (targetValue.dataset.mode === 'confirmation' && Number(targetValue.value) < 1) {
            removeButton.click();
        }
      }

      if (eventTarget.classList.contains('js-decrement-button')) {
        if (targetValue.getAttribute('value') === '1' && targetValue.getAttribute('min') === '1') {
            removeButton.click();
        }
      }
```

The conde can be simplified, the firs `if` avoid `3 ifs`

2023-09-06 16:27 UTC, djoelleuch approved these changes
Hello @tblivet  , 
LGTM , 
If you change from 1 to 0 using arrows, the product is deleted. :heavy_check_mark: 
If you change from 1 to 0 using the input value, the product is deleted. :heavy_check_mark: 
If you have a product with a minimal quantity set to 2 and you change it to 1, you have an error.
:heavy_check_mark: 
**[but i think that the error message disappear too fast  ]** 


 

https://github.com/PrestaShop/hummingbird/assets/115152460/1bd6c18e-33ad-4920-9d1e-ec41959416bf

It's QA approved ✔️
thank you !

2023-09-07 10:12 UTC, merged