Add classes to make menu elements tall as parent
PrestaShop/hummingbird pull request #547
Opened 2023-09-05 13:17 UTC by rodriciru

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Please be specific when describing this change. What did you change? Why?
| Type?             | bug fix / improvement / new feature / refactor
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | Indicate how to verify that this change works as expected.

2023-09-06 12:15 UTC, tblivet requested changes
Hello 👋
I think you want to do this modification, because if the logo is higher than the menu, we cannot access the submenu ? Is it right ?
Your modification looks good, but with those, the logo is no longer vertically centered.
So I suggest adding some classes to fix it.

2023-09-06 12:16 UTC, tblivet requested changes

2023-09-06 12:16 UTC, tblivet commented on templates/_partials/header.tpl
> +      <div class="row gx-2 {$headerBottomName}__row">
```suggestion
      <div class="row gx-2 align-items-stretch {$headerBottomName}__row">
```

2023-09-06 12:16 UTC, tblivet commented on templates/_partials/header.tpl
>          <div class="col-auto logo order-xl-1 ms-lg-0 ms-2 me-lg-0 me-auto">
```suggestion
        <div class="d-flex align-items-center col-auto logo order-xl-1 ms-lg-0 ms-2 me-lg-0 me-auto">
```

2023-09-07 07:57 UTC, rodriciru commented
Thanks tblivet. You were right in your suggestions. Align-items-stretch it's not necessary, because in flex normal it's the same as stretch, but it doesn't matter.
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#values

2023-09-07 08:02 UTC, tblivet approved these changes

2023-09-07 15:58 UTC, matks approved these changes

2023-09-11 14:25 UTC, paulnoelcholot commented
Hello @rodriciru,

I tested your PR and it's good for me! :tada: 

Thanks!

2023-09-11 14:26 UTC, paulnoelcholot approved these changes

2023-09-12 05:17 UTC, merged