Fix logo size
PrestaShop/hummingbird pull request #606
Opened 2024-03-08 09:39 UTC by boherm

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | After tests review for https://github.com/PrestaShop/hummingbird/pull/600#pullrequestreview-1898190625,<br>we need to fix the logo size when the uploaded image is taller than longer.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Not yet.
| Sponsor company   | PrestaShop SA
| How to test?      | See @florine2623 review in https://github.com/PrestaShop/hummingbird/pull/600#pullrequestreview-1898190625

2024-03-08 14:36 UTC, SharakPL requested changes

2024-03-08 14:36 UTC, SharakPL commented on templates/_partials/helpers.tpl
> +      class="logo"
```suggestion
      class="logo img-fluid"
```
This class is required

2024-03-08 16:26 UTC, tblivet submitted a review, later dismissed
Looks good to me 👍
If we limit the height, maybe we also need to do the same for the width ?
Like `max-width: 150px;` ?

2024-03-08 17:00 UTC, SharakPL commented
> Like `max-width: 150px;` ?

Yes, but from my experience it should be around 250px

2024-03-08 17:21 UTC, SharakPL approved these changes

2024-03-11 15:20 UTC, AureRita commented
Hi @boherm 

Thank you for your PR, currently I tested it and, yes, the logo is a little bit smaller but I think it's not enought as you can see : 

![image](https://github.com/PrestaShop/hummingbird/assets/100699445/db4ba724-1458-4efd-8235-3de7b838f8bb)


FYI : you can scroll under the logo 

Can you correct it ? 

Waiting for your feedback

2024-03-13 16:54 UTC, boherm commented
Hi @AureRita, thanks for the review!

This is only on the homepage or on a specific page?

It looks like you haven't properly rebuild hummingbird theme or don't clear the browser cache. 🤔
Have you done this steps?

@SharakPL, @tblivet,
So, do you prefer adding `max-width: 250px;` property and also removing `.img-fluid` (that is totally bypassed by this rule)?

2024-03-13 21:36 UTC, SharakPL requested changes

2024-03-13 21:36 UTC, SharakPL commented on src/scss/custom/layout/_header-bottom.scss
> +    }
```suggestion
  .navbar-brand {
    padding: 0;
    max-width: 250px;
    max-height: max(50px, 12vh);

    .logo {
      max-height: inherit;
    }
```
This should work nicely.

2024-03-14 13:25 UTC, SharakPL approved these changes

2024-03-14 17:08 UTC, AureRita approved these changes
Hi @boherm 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(139).webm](https://github.com/PrestaShop/hummingbird/assets/100699445/1745c759-1bf1-4621-9196-e030484d85a9)

Tested on develop and 8.1.x

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

2024-03-14 22:47 UTC, merged