Fix: issue-340
PrestaShop/hummingbird pull request #627
Opened 2024-05-17 16:27 UTC by tblivet

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix https://github.com/PrestaShop/hummingbird/issues/340
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | 
| Fixed ticket?     | Fix https://github.com/PrestaShop/hummingbird/issues/340
| Sponsor company   | @PrestaShopCorp
| How to test?      | ⬇️

Most of the points described in the issue have already been addressed. The remaining ones have been tackled as follows:
- Enhanced pagination to prevent overflow on mobile devices:
  ![image](https://github.com/PrestaShop/hummingbird/assets/110676325/69b37d40-667a-4c03-9f4b-c2c741e1e36d)
- Added a Bootstrap breakpoint to provide more flexibility on small devices (use to improve product list on mobile).
- Updated product list display based on page layouts.
- Improved mobile display of the product list to feature only one product per row on mobile devices.
![image](https://github.com/PrestaShop/hummingbird/assets/110676325/aaafc11f-3317-426b-89a2-b84530954a92)

2024-05-18 05:30 UTC, nicosomb approved these changes, later dismissed

2024-05-20 05:50 UTC, Hlavtox requested changes
Please keep one column for mobile. In the issue, it was just a suggestion from the author.

2024-05-20 07:30 UTC, tblivet commented
> Please keep one column for mobile. In the issue, it was just a suggestion from the author.

Hi @Hlavtox, I don't really understand, you want me to remove one column for mobile?
I think it's a good optimization as it will concern only devices with screen width < 375. What do you think?

2024-05-20 07:52 UTC, tblivet commented
@Hlavtox, I think removing it is not a good idea because with 2 products per line on very small devices, we really lose in terms of visibility. As you say, we can fit more data, but we display more data in a bad way.
I suggest keeping this in place but reducing the breakpoint to 360.
With the previous value of 375, the new iPhones will display 2 products per line as it will trigger if < 375. If we lower the value to 360, we will also cover Galaxy, and some other phones, which have a width of 360 for their latest models. This way, one column will only display for small and older devices.
https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide

I think it's a good compromise. What do you think?

2024-05-20 08:00 UTC, Hlavtox commented
@tblivet Yeah! Good solution. :-) Do you want to move the breakpoint or add another one?

2024-05-20 08:03 UTC, tblivet commented
@Hlavtox, Perfect 👍 No, just move it because it's already a new breakpoint!

2024-05-20 08:32 UTC, nicosomb approved these changes

2024-05-20 09:37 UTC, Hlavtox approved these changes

2024-05-20 14:31 UTC, boherm approved these changes

2024-06-06 10:03 UTC, florine2623 approved these changes
Hello @tblivet ,

Thanks for the PR.

When I try on desktop screen, the 3 dots button doesn't work :

https://github.com/PrestaShop/hummingbird/assets/16019289/a8704ec6-6de7-4737-8c33-288845bf32a4

On mobile 320px size, the pagination design is as expected. 

But it doesn't work so well. The 3-dots button doesn't always work.

https://github.com/PrestaShop/hummingbird/assets/16019289/89ec259d-2c96-4837-8c76-a3cb1a2b2888

Although this is not blocking, before this PR, it was already like this. It can be fixed later.

The products are well displayed on mobile size.

It is QA ✅

2024-06-06 10:13 UTC, tblivet commented
Thank you, @florine2623 🙏
The three dots are just there to indicate that there are pages between page X and page Y.
They allow us to keep all the pagination on a single line, instead of showing every page. So, it's normal if they do nothing, they're just visual elements.

2024-06-06 10:15 UTC, merged