Removed .env configuration
PrestaShop/hummingbird pull request #629
Opened 2024-05-21 09:14 UTC by nicosomb

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Removed .env configuration
| Type?             | improvement 
| BC breaks?        | no
| Deprecations?     | no
| Sponsor company   | PrestaShop SA

This PR allows to fix the issue I have here https://github.com/PrestaShop/PrestaShop/pull/36198#issuecomment-2122042886 to embed HB in PrestaShop core.

2024-05-21 09:15 UTC, nicosomb commented
I know that some variables will remain empty, but the build seems ok like this. 

Removing .env dependency will help us to ship hummingbird in prestashop core.

2024-05-21 09:17 UTC, Hlavtox requested changes
The env configuration was added for a reason. 🤔 Ping @Oksydan @NeOMakinG

2024-05-21 09:18 UTC, nicosomb commented
I know that there were some reasons ... but we can't find them.

2024-05-21 09:24 UTC, Hlavtox commented
PR that introduced this, with discussion - https://github.com/PrestaShop/hummingbird/pull/67

2024-05-21 09:29 UTC, nicosomb commented
OK so it seems that you warned about this issue...

2024-05-23 22:58 UTC, Oksydan commented
@nicosomb .env file is being used by webpack-dev-server mostly to improve DX. Why would you like to get ride of this like this 🤔.

2024-05-24 06:11 UTC, nicosomb commented
@Oksydan I understand, but can you tell us how can we ship it in PrestaShop core please ? 

We want to add Hummingbird as a dependency in composer.json (see my PR here https://github.com/PrestaShop/PrestaShop/pull/36198). So we have to know how to fill the .env file during the assets build process.

2024-05-27 07:56 UTC, Oksydan commented
Hmmmmm we could pass arguments in the compilation process. If the process is building a theme, we could simply not check if the `.env` file exists, otherwise check for its existence and terminate the process. For missing values from env, we could set default values:
```javascript 
const {
  PORT: port = null,
  PUBLIC_PATH: publicPath = null,
  SERVER_ADDRESS: serverAddress = null,
  SITE_URL: siteURL = null,
} = process.env;
```
THB we do not need these values in the compilation process. It is only required for the development process.

2024-05-27 08:21 UTC, nicosomb commented
@Oksydan thank you for the details. I will improve my PR.

2024-06-13 10:20 UTC, boherm commented on templates/catalog/_partials/miniatures/product.tpl
> +            {if $product.add_to_cart_url}
This is related to this PR: https://github.com/prestashop/hummingbird/pull/609/

2024-06-13 11:53 UTC, nicosomb commented on templates/catalog/_partials/miniatures/product.tpl
> +            {if $product.add_to_cart_url}
I know that. But it seems that it breaks UI tests.

2024-06-13 12:16 UTC, boherm commented on templates/catalog/_partials/miniatures/product.tpl
> +            {if $product.add_to_cart_url}
I think that's an issue about UI tests then.
If we merge your diff, we reintroduce the "Add to cart" button for combinations products, and his buggy behaviour in that particular case 🤔

But anyway, I don't block your PR, just I prefer to warn you about this! 😉

2024-07-02 14:03 UTC, nicosomb commented
@Hlavtox we have to go forward, could you please remove your request approval? 
if necessary, we can still open a new PR later.

2024-07-02 15:18 UTC, Hlavtox commented on templates/catalog/_partials/miniatures/product.tpl
> +            {if $product.add_to_cart_url}
I think the change is legit, add to cart url should be handled on product lazy array settings. For combination, it's availability depends on prestashop settings (enable add to cart button in listings when product has combinations on/off).

2024-07-02 15:18 UTC, Hlavtox approved these changes

2024-07-03 07:19 UTC, florine2623 commented
Hello @nicosomb ,

What are the steps to reproduce ?
Do we just need to make sure the theme is well installed ?

2024-07-04 13:59 UTC, florine2623 approved these changes
Hello @nicosomb ,

Hummingbird is well installed.
Made an order with all types of products, order process is working as expected.

LGTM ✅ 
Thanks!

2024-07-04 14:05 UTC, merged